export const Skills = {
    java: {id: 0, name: 'Java', type:'primaryLanguage'},
    cSharp: {id: 1, name: 'C#', type:'primaryLanguage'},
    javascript: {id: 2, name: 'Javascript', type:'primaryLanguage'},
    
    json: {id: 3, name: 'JSON', type: 'secondaryLanguage'},
    xml: {id: 3, name: 'XML', type: 'secondaryLanguage'},
    sql: {id: 4, name: 'SQL', type: 'secondaryLanguage'},
    html: {id: 5, name: 'HTML', type: 'secondaryLanguage'},
    css: {id: 6, name: 'CSS', type: 'secondaryLanguage'},
    jsx: {id: 7, name: 'JSX', type: 'secondaryLanguage'},
    jsp: {id: 8, name: 'JSP', type: 'secondaryLanguage'},
    react: {id: 9, name: 'React', type: 'library_framework_javascript'},
    angular: {id: 10, name: 'Angular', type: 'library_framework_javascript'},
    node: {id: 11, name: 'Node', type: 'library_framework_javascript'},
    backbone: {id: 12, name: 'Backbone', type: 'library_framework_javascript'},
    jQuery: {id: 13, name: 'JQuery', type: 'library_framework_javascript'},
    lodash: {id: 14, name: 'Lodash', type: 'library_framework_javascript'},
    underscore: {id: 15, name: 'Underscore', type: 'library_framework_javascript'},
    d3: {id: 16, name: 'D3', type: 'library_framework_javascript'},
    jest: {id: 17, name: 'Jest', type: 'library_framework_javascript'},
    jasmine: {id: 18, name: 'Jasmine', type: 'library_framework_javascript'},
    spring: {id: 19, name: 'Spring', type: 'library_framework_java'},
    jpa: {id: 20, name: 'JPA', type: 'library_framework_java'},
    hibernate: {id: 21, name: 'Hibernate', type: 'library_framework_java'},
    entity: {id: 22, name: 'Entity', type: 'library_framework_java'},
    jUnit: {id: 23, name: 'JUnit', type: 'library_framework_java'},
    hybris: {id: 24, name: 'Hybris', type: 'library_framework_java'},
    redux: {id: 52, name: 'Redux', type: 'library_framework_javascript'},
    styled: {id: 53, name: 'Styled Components', type: 'library_framework_javascript'},
    
    mySql: {id: 25, name: 'MySql', type: 'database'},
    sqlServer: {id: 26, name: 'SqlServer', type: 'database'},
    oracle: {id: 27, name: 'Oracle', type: 'database'},
    rds: {id: 51, name: 'Amazon RDS', type: 'database'},
    
    ant: {id: 28, name: 'Ant', type: 'build_tool'},
    maven: {id: 29, name: 'Maven', type: 'build_tool'},
    gradle: {id: 30, name: 'Maven', type: 'build_tool'},
    npm: {id: 54, name: 'Node Package Manager', type: 'build_tool'},

    git: {id: 31, name: 'Git', type: 'source_control'},
    subversion: {id: 32, name: 'Subversion', type: 'source_control'},
    perforce: {id: 33, name: 'Perforce', type: 'source_control'},

    jira: {id: 34, name: 'Jira', type: 'alm'},
    v1: {id: 35, name: 'Version One', type: 'alm'},
    tfs: {id: 36, name: 'Team Foundation Server', type: 'alm'},

    intelliJ: {id: 37, name: 'IntelliJ IDEA', type: 'ide'},
    eclipse: {id: 38, name: 'Eclipse', type: 'ide'},
    visualStudio: {id: 39, name: 'Visual Studio', type: 'ide'},
    vSCode: {id: 40, name: 'Visual Studio Code', type: 'ide'},
    
    jenkins: {id: 41, name: 'Jenkins', type: 'cicd'},
    gitLab: {id: 42, name: 'GitLab', type: 'cicd'},
    bitbucket: {id: 43, name: 'Bitbucket', type: 'cicd'},

    tomcat: {id: 44, name: 'Tomcat', type: 'servers'},
    lambda: {id: 45, name: 'AWS Lambda', type: 'servers'},
    
    windows: {id: 46, name: 'Windows', type: 'os'},
    mac: {id: 47, name: 'Mac', type: 'os'},
    linux: {id: 48, name: 'Linux', type: 'os'},
    
    agile: {id: 49, name: 'Agile', type: 'other'},
    tdd: {id: 50, name: 'Test Driven Development', type: 'other'},
}